import numpy as np
marks=np.array([[60,70,80],[70,80,90],[70,80,60]])
print(marks)
print(np.mean(marks))
print("shape:",np.shape(marks))
result=np.mean(marks,axis=0)
print(result)
result1=np.mean(marks,axis=1)
print(result1)
print(result.shape)
print(result1.shape)